// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import model.GameState;

/************************************************************/
/**
 * 
 */
public class BlackJack {
	/**
	 * 
	 */
	public GameState gameState;

	/**
	 * 
	 */
	public void getGameState() {
	}

	/**
	 * 
	 */
	public void setGameState() {
	}
};
