// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import model.GameState;

/************************************************************/
/**
 * 
 */
public class BlackJack {
	/**
	 * 
	 */
	public GameState gameState;

	/**
	 * 
	 */
	public GameState getGameState() {
		return gameState;
	}

	/**
	 * 
	 */
	public void setGameState(GameState gameState) {
		this.gameState= gameState;
	}
};
