// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import model.Suite;
import model.Value;

/************************************************************/
/**
 * 
 */
public class Card {
	/**
	 * 
	 */
	public Value value;
	/**
	 * 
	 */
	public Suite suiteType;

	/**
	 * 
	 */
	public void getSuiteType() {
	}

	/**
	 * 
	 */
	public void setSuiteType() {
	}

	/**
	 * 
	 */
	public void getValue() {
	}

	/**
	 * 
	 */
	public void setValue() {
	}
};
