// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import model.Player;

/************************************************************/
/**
 * 
 */
public class Dealer extends Player {
	/**
	 * 
	 */
	public Boolean isDistributed;

	/**
	 * 
	 */
	public void drawCards() {
	}

	/**
	 * 
	 */
	public void distribute() {
	}
};
