// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import model.Card;

/************************************************************/
/**
 * 
 */
public class Deck {
	/**
	 * 
	 */
	public Card Card;

	/**
	 * 
	 */
	public void addCard() {
	}

	/**
	 * 
	 */
	
	public void shuffleCard() {
	}

	/**
	 * 
	 */
	public void removeCard() {
	}
};
