// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import model.Card;

/************************************************************/
/**
 * 
 */
public class Hand {
	/**
	 * 
	 */
	public int totalValue;/**
					 * 
					 */
	public boolean isPlayer;/**
						 * 
						 */
	public boolean bothEqual;
	/**
	 * 
	 */
	public Card card;/**
						 * 
						 */
	public int totalCards;/**
					 * 
					 */
	public boolean isPlacedBet;/**
						 * 
						 */
	public boolean isStart;
};
