// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	public String name;

	/**
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * 
	 * @return name 
	 */
	public void setName(String name) {
		this.name = name;
	}
};
