// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import model.Decision;

/************************************************************/
/**
 * 
 */
public class Stand extends Decision {

	/**
	 * 
	 */
	public void action() {
	}
};
