// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import model.Player;

/************************************************************/
/**
 * 
 */
public class User extends Player {
	/**
	 * 
	 */
	public int balance;/**
				 * 
				 */
	public int score;/**
				 * 
				 */
	public boolean isPlacedBet;
	/**
	 * 
	 */
	public void getScore() {
	}

	/**
	 * 
	 */
	public void setScore() {
	}

	/**
	 * 
	 */
	public void placeBet() {
	}
};
